# Generated by Django 6.0.1 on 2026-02-12 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_analytics', '0001_initial'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecord',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruiter.recruiter'),
        ),
    ]
